In [1]:
import yfinance as yf
import pandas as pd

In [2]:
s=yf.Search("Reliance",enable_fuzzy_query=True, lists_count=30,max_results=30
                       news_count=0,
                       )
pd.DataFrame(s.quotes)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2510620158.py, line 1)

In [3]:
s.__dict__

NameError: name 's' is not defined

In [5]:
l=yf.Lookup("Reliance").get_all()
l

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
RELI,NCM,https://finance.yahoo.com/sector/financial_ser...,Financial Services,equity,20008,0.026800,3.272280,0.845800,"Reliance Global Group, Inc."
RS,NYQ,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20007,5.464996,2.011408,277.165009,"Reliance, Inc."
RELINFRA.NS,NSI,https://finance.yahoo.com/sector/utilities,Utilities,equity,20006,0.690002,0.308422,224.410004,RELIANCE INFRASTRUCTU LTD
0EU.F,FRA,https://finance.yahoo.com/sector/industrials,Industrials,equity,20005,0.060000,2.884624,2.140000,Reliance Worldwide Corp. Ltd. R
0P0000TGJZ.BO,BSE,NaN,NaN,mutualfund,20004,0.004101,0.012400,33.075199,0P0000TGJZ.BO
RPOWER.NS,NSI,https://finance.yahoo.com/sector/utilities,Utilities,equity,20004,-0.480000,-1.075268,44.160000,RELIANCE POWER LTD.
FSRL,PNK,https://finance.yahoo.com/sector/financial_ser...,Financial Services,equity,20003,-0.009999,-0.095413,10.470000,"First Reliance Bancshares, Inc."
0P0000NPP0.BO,BSE,NaN,NaN,mutualfund,20003,0.215000,0.353634,61.012299,0P0000NPP0.BO
RELIW,NCM,https://finance.yahoo.com/sector/financial_ser...,Financial Services,equity,20003,0.000000,0.000000,0.035000,"Reliance Global Group, Inc. - S"
0P0000NPKG.BO,BSE,NaN,NaN,mutualfund,20003,0.494297,0.899731,55.432598,0P0000NPKG.BO
0P0000NPLM.BO,BSE,NaN,NaN,mutualfund,20003,0.280502,0.450923,62.486801,0P0000NPLM.BO
RS6.DU,DUS,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20002,3.600006,1.575495,232.100006,Reliance Inc. R
RS6.BE,BER,https://finance.yahoo.com/sector/basic_materials,Basic Materials,equity,20002,3.699997,1.619255,232.199997,Reliance Inc. R
RWC.AX,ASX,https://finance.yahoo.com/sector/industrials,Industrials,equity,20002,0.060000,1.550392,3.930000,RWC CORP FPO [RWC]
RPOWER.BO,BSE,https://finance.yahoo.com/sector/utilities,Utilities,equity,20002,-0.500000,-1.119069,44.180000,RELIANCE POWER LTD.
RELIANCE.NS,NSI,https://finance.yahoo.com/sector/energy,Energy,equity,20002,50.000000,3.529080,1466.800049,RELIANCE INDUSTRIES LTD
RIIL.BO,BSE,https://finance.yahoo.com/sector/industrials,Industrials,equity,20002,6.000000,0.667631,904.700012,RELIANCE INDUSTRIAL INFRASTRUC
RCOM.NS,NSI,https://finance.yahoo.com/sector/communication...,Communication Services,equity,20002,0.000000,0.000000,1.390000,RELIANCE COMMUNICATIONS L
RLI.MU,MUN,https://finance.yahoo.com/sector/energy,Energy,equity,20001,2.800003,5.223886,56.400002,RELIANCE INDUSTRIES LTD. R
RCOM.BO,BSE,https://finance.yahoo.com/sector/communication...,Communication Services,equity,20001,-0.020000,-1.428570,1.380000,RELIANCE COMMUNICATIONS LTD.
RHFL.BO,BSE,https://finance.yahoo.com/sector/financial_ser...,Financial Services,equity,20001,0.000000,0.000000,3.650000,Reliance Home Finance Limited
0EU.BE,BER,https://finance.yahoo.com/sector/industrials,Industrials,equity,20001,0.020000,0.999999,2.020000,Reliance Worldwide Corp. Ltd. R
RIGDL.XC,CXE,NaN,NaN,equity,20001,0.599998,0.909089,66.599998,Reliance Industries Ltd
0P0000NPOT.BO,BSE,NaN,NaN,mutualfund,20001,0.241001,0.479309,50.521999,0P0000NPOT.BO
0P0000NPKH.BO,BSE,NaN,NaN,mutualfund,20001,0.116501,0.330462,35.370399,0P0000NPKH.BO

In [4]:
l

NameError: name 'l' is not defined

In [ ]:
exchanges=['BSE','NSI']
l.query('exchange.isin(@exchanges)')["quoteType shortName".split()]

                quoteType                      shortName
symbol
RELIANCE.NS        equity        RELIANCE INDUSTRIES LTD
RPOWER.BO          equity            RELIANCE POWER LTD.
0P0000NPMX.BO  mutualfund                  0P0000NPMX.BO
0P0000TGJZ.BO  mutualfund                  0P0000TGJZ.BO
0P0000NPP0.BO  mutualfund                  0P0000NPP0.BO
0P0000NPLM.BO  mutualfund                  0P0000NPLM.BO
0P0000NPKG.BO  mutualfund                  0P0000NPKG.BO
RELIANCE.BO        equity       RELIANCE INDUSTRIES LTD.
RELINFRA.NS        equity      RELIANCE INFRASTRUCTU LTD
0P0000TGKS.BO  mutualfund                  0P0000TGKS.BO
RHFL.BO            equity  Reliance Home Finance Limited
RCOM.BO            equity   RELIANCE COMMUNICATIONS LTD.

In [3]:
s=yf.Ticker('0P0001PR8B.BO')

In [7]:
s.info

{'address1': 'Bandra (East), Mumbai',
 'address2': 'C-38 & 39, G Block, Bandra Kurla Complex,',
 'address3': '9th Floor, Crescenzo,',
 'phone': '022 - 61793000',
 'companyOfficers': [],
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 18.5528,
 'regularMarketPreviousClose': 18.5528,
 'trailingPE': 28.943983,
 'yield': 0.0,
 'ytdReturn': -6.91712,
 'fiftyTwoWeekLow': 14.9928,
 'fiftyTwoWeekHigh': 20.1718,
 'fiftyDayAverage': 18.512434,
 'twoHundredDayAverage': 17.856035,
 'currency': 'INR',
 'tradeable': False,
 'morningStarOverallRating': 0,
 'morningStarRiskRating': 0,
 'annualReportExpenseRatio': 0.0,
 'fundInceptionDate': 1663718400,
 'annualHoldingsTurnover': 0.40919998,
 'quoteType': 'MUTUALFUND',
 'symbol': '0P0001PR8B.BO',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Fund',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'NONE',
 'shortName': '0P0001PR8B.BO',
 'longName': 'SBI Nifty Smallcap 250 Index Dir IDCW-T',
 'marketState': 'POSTPOST',
 'fiftyDayAverageChange': 0.055965424,
 'fiftyDayAverageChangePercent': 0.0030231262,
 'twoHundredDayAverageChange': 0.7123642,
 'twoHundredDayAverageChangePercent': 0.03989487,
 'sourceInterval': 10,
 'exchangeDataDelayedBy': 15,
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 1663731900000,
 'regularMarketChange': 0.0156002045,
 'fullExchangeName': 'BSE',
 'fiftyTwoWeekLowChange': 3.5755997,
 'fiftyTwoWeekLowChangePercent': 0.2384878,
 'fiftyTwoWeekRange': '14.9928 - 20.1718',
 'fiftyTwoWeekHighChange': -1.6034012,
 'fiftyTwoWeekHighChangePercent': -0.079487264,
 'fiftyTwoWeekChangePercent': -5.897975,
 'dividendYield': 0.0,
 'trailingThreeMonthReturns': -1.74247,
 'epsTrailingTwelveMonths': 0.64152884,
 'corporateActions': [],
 'regularMarketTime': 1759708800,
 'exchange': 'BSE',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.08408545,
 'regularMarketPrice': 18.5684,
 'trailingPegRatio': None}

In [7]:
import ipywidgets as w


mag7=yf.Tickers('aapl msft goog tsla nvda meta'.split())

In [12]:
subs=[]

In [13]:

def msg_hdr(e):
    print(e)

subs.append(mag7.live(msg_hdr,verbose=True))

Connected to WebSocket.
Subscribed to symbols: ['AAPL', 'MSFT', 'GOOG', 'TSLA', 'NVDA', 'META']
Listening for messages...
{'id': 'AAPL', 'price': 263.495, 'time': '1760978115000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4413185, 'day_volume': '54582115', 'change': 11.205002, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.34, 'time': '1760978120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.53740597, 'day_volume': '5377718', 'change': 2.7600098, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.64, 'time': '1760978120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.22923161, 'day_volume': '75183966', 'change': 0.41999817, 'last_size': '100', 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.12, 'time': '1760978118000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0948982, 'day_volume': '38922476', 'change': 4.8099976, 'price_hint': '2'}
{'id': 'META', 'price': 730.6325, 'time': '1760978114000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9134109, 'day_volume': '4734271', 'change': 13.717529, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.365, 'time': '1760978120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54226667, 'day_volume': '5378992', 'change': 2.7849731, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.1, 'time': '1760978119000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.304233, 'day_volume': '6153212', 'change': 3.3100128, 'last_size': '100', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.495, 'time': '1760978115000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4413185, 'day_volume': '54582175', 'change': 11.205002, 'price_hint': '2'}
{'id': 'META', 'price': 730.6325, 'time': '1760978114000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9134109, 'day_volume': '4734331', 'change': 13.717529, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.64, 'time': '1760978121000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.22923161, 'day_volume': '75184813', 'change': 0.41999817, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.125, 'time': '1760978121000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0960375, 'day_volume': '38922874', 'change': 4.8150024, 'last_size': '350', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.495, 'time': '1760978121000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4413185, 'day_volume': '54584977', 'change': 11.205002, 'last_size': '100', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.365, 'time': '1760978120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54226667, 'day_volume': '5379052', 'change': 2.7849731, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.615, 'time': '1760978122000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21559487, 'day_volume': '75187851', 'change': 0.39500427, 'last_size': '500', 'price_hint': '2'}
{'id': 'META', 'price': 730.6325, 'time': '1760978114000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9134109, 'day_volume': '4734338', 'change': 13.717529, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.07, 'time': '1760978121000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0835196, 'day_volume': '38923131', 'change': 4.76001, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.1, 'time': '1760978119000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.304233, 'day_volume': '6153315', 'change': 3.3100128, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.365, 'time': '1760978120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54226667, 'day_volume': '5379114', 'change': 2.7849731, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4433026, 'day_volume': '54586544', 'change': 11.210007, 'last_size': '450', 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.01, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0698624, 'day_volume': '38926658', 'change': 4.700012, 'last_size': '2330', 'price_hint': '2'}
{'id': 'META', 'price': 730.6325, 'time': '1760978114000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9134109, 'day_volume': '4734371', 'change': 13.717529, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.615, 'time': '1760978122000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21559015, 'day_volume': '75187932', 'change': 0.39500427, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.1, 'time': '1760978119000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.304233, 'day_volume': '6153332', 'change': 3.3100128, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4433026, 'day_volume': '54586826', 'change': 11.210007, 'last_size': '100', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.35, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.5393431, 'day_volume': '5379250', 'change': 2.7699585, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.61, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21285853, 'day_volume': '75188976', 'change': 0.3899994, 'last_size': '100', 'price_hint': '2'}
{'id': 'META', 'price': 730.6325, 'time': '1760978114000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9134109, 'day_volume': '4734403', 'change': 13.717529, 'price_hint': '2'}
{'id': 'TSLA', 'price': 443.98, 'time': '1760978123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0630337, 'day_volume': '38933686', 'change': 4.6700134, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.1, 'time': '1760978119000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.304233, 'day_volume': '6153333', 'change': 3.3100128, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.53, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4551926, 'day_volume': '54589567', 'change': 11.2400055, 'last_size': '100', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379366', 'change': 2.789978, 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109209, 'day_volume': '4734524', 'change': 13.700012, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.62, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21831344, 'day_volume': '75191501', 'change': 0.3999939, 'last_size': '110', 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.02, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0721339, 'day_volume': '38934702', 'change': 4.7099915, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.105, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.306205, 'day_volume': '6153541', 'change': 3.3150177, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379406', 'change': 2.789978, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.53, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4551926, 'day_volume': '54589984', 'change': 11.2400055, 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4734541', 'change': 13.700012, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.0612, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.081512, 'day_volume': '38935215', 'change': 4.75119, 'last_size': '300', 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.62, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21831344, 'day_volume': '75192350', 'change': 0.3999939, 'last_size': '190', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.08, 'time': '1760978126000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2963448, 'day_volume': '6153945', 'change': 3.2899933, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379452', 'change': 2.789978, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5201, 'time': '1760978126000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4512734, 'day_volume': '54592156', 'change': 11.230118, 'last_size': '288', 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.61, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21285853, 'day_volume': '75193195', 'change': 0.3899994, 'last_size': '400', 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978125000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4734546', 'change': 13.700012, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.09, 'time': '1760978126000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0880697, 'day_volume': '38935534', 'change': 4.779999, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.08, 'time': '1760978126000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2963448, 'day_volume': '6153996', 'change': 3.2899933, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379457', 'change': 2.789978, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.515, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.449342, 'day_volume': '54593484', 'change': 11.225021, 'last_size': '100', 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.605, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21012689, 'day_volume': '75194390', 'change': 0.3849945, 'last_size': '500', 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4734885', 'change': 13.700012, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.06, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.081241, 'day_volume': '38936536', 'change': 4.75, 'last_size': '300', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.49, 'time': '1760978129000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.439159, 'day_volume': '54594941', 'change': 11.199997, 'last_size': '100', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379463', 'change': 2.789978, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.07, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2924126, 'day_volume': '6154198', 'change': 3.280014, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.6, 'time': '1760978129000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.2074036, 'day_volume': '75194712', 'change': 0.38000488, 'last_size': '100', 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4734937', 'change': 13.700012, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.0119, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0702931, 'day_volume': '38936939', 'change': 4.7019043, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.07, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2924126, 'day_volume': '6156122', 'change': 3.280014, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5, 'time': '1760978129000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4434786, 'day_volume': '54596330', 'change': 11.210007, 'last_size': '190', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379465', 'change': 2.789978, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.0119, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0702931, 'day_volume': '38937006', 'change': 4.7019043, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.6094, 'time': '1760978130000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21253373, 'day_volume': '75195157', 'change': 0.3894043, 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4735026', 'change': 13.700012, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.07, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2924126, 'day_volume': '6156265', 'change': 3.280014, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5099, 'time': '1760978131000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.447396, 'day_volume': '54597818', 'change': 11.219894, 'last_size': '200', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379477', 'change': 2.789978, 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4735027', 'change': 13.700012, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.605, 'time': '1760978130000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21012689, 'day_volume': '75196693', 'change': 0.3849945, 'last_size': '100', 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.0119, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0702931, 'day_volume': '38937073', 'change': 4.7019043, 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.5099, 'time': '1760978131000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4472218, 'day_volume': '54597959', 'change': 11.219894, 'last_size': '100', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.37, 'time': '1760978124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.54324114, 'day_volume': '5379500', 'change': 2.789978, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.07, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2924126, 'day_volume': '6156352', 'change': 3.280014, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.0992, 'time': '1760978131000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0901675, 'day_volume': '38937708', 'change': 4.789215, 'last_size': '200', 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.605, 'time': '1760978130000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21012689, 'day_volume': '75196842', 'change': 0.3849945, 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4735069', 'change': 13.700012, 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.07, 'time': '1760978128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.2924126, 'day_volume': '6156353', 'change': 3.280014, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.375, 'time': '1760978132000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.5442157, 'day_volume': '5380786', 'change': 2.794983, 'last_size': '235', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.48, 'time': '1760978132000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.435379, 'day_volume': '54599973', 'change': 11.190018, 'last_size': '100', 'price_hint': '2'}
{'id': 'META', 'price': 730.615, 'time': '1760978127000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9109675, 'day_volume': '4735102', 'change': 13.700012, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.625, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.22104508, 'day_volume': '75198032', 'change': 0.40499878, 'last_size': '300', 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.07, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0835196, 'day_volume': '38938798', 'change': 4.76001, 'last_size': '300', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.105, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.306205, 'day_volume': '6156834', 'change': 3.3150177, 'last_size': '300', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.51, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.44727, 'day_volume': '54600621', 'change': 11.2200165, 'last_size': '340', 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.375, 'time': '1760978132000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.5442157, 'day_volume': '5380829', 'change': 2.794983, 'price_hint': '2'}
{'id': 'TSLA', 'price': 444.07, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.0835196, 'day_volume': '38939062', 'change': 4.76001, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.63, 'time': '1760978134000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.2237767, 'day_volume': '75198618', 'change': 0.41000366, 'last_size': '100', 'price_hint': '2'}
{'id': 'META', 'price': 730.565, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.9039949, 'day_volume': '4735815', 'change': 13.650024, 'price_hint': '2'}
{'id': 'MSFT', 'price': 516.375, 'time': '1760978134000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.5442157, 'day_volume': '5380986', 'change': 2.794983, 'last_size': '100', 'price_hint': '2'}
{'id': 'AAPL', 'price': 263.56, 'time': '1760978134000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 4.4670835, 'day_volume': '54607643', 'change': 11.270004, 'last_size': '100', 'price_hint': '2'}
{'id': 'GOOG', 'price': 257.105, 'time': '1760978133000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 1.306205, 'day_volume': '6156857', 'change': 3.3150177, 'price_hint': '2'}
{'id': 'NVDA', 'price': 183.62, 'time': '1760978135000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 1, 'change_percent': 0.21831344, 'day_volume': '75200757', 'change': 0.3999939, 'last_size': '100', 'price_hint': '2'}

In [ ]:
%gui asyncio

In [ ]:
import asyncio
def wait_for_change(widget, value):
    future = asyncio.Future()
    def getvalue(change):
        # make the new value available
        future.set_result(change.new)
        widget.unobserve(getvalue, value)
    widget.observe(getvalue, value)
    return future

In [ ]:
from ipywidgets import IntSlider
slider = IntSlider()
display(slider)

async def f():
    for i in range(10):
        print('did work %s'%i)
        x = await wait_for_change(slider, 'value')
        print('async function continued with value %s'%x)

asyncio.ensure_future(f())

# slider